# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo #last=version
    container_name: mongo
    volumes:
    - ./mongodb:/data/db
    ports: 
    - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: viet2799

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: viet2799
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false


 # docker-compose -f mongo-compose.yaml up -d